apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  tssc/gitops: qm33gqzxa-nodejs 
  janus-idp.io/tekton: qm33gqzxa-nodejs
  backstage.io/kubernetes-id: qm33gqzxa-nodejs
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: qm33gqzxa-nodejs
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml