apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: qm33gqzxa-nodejs
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: qm33gqzxa-nodejs 
  name: qm33gqzxa-nodejs
spec:
  ports:
  - port: 3001 
    targetPort: 3001 
  selector:
    app.kubernetes.io/instance: qm33gqzxa-nodejs 
